//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAT_PRodukcja.dbProdukcjaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artykuły
    {
        public int Lp { get; set; }
        public string Nazwa_art { get; set; }
        public string Opis { get; set; }
        public Nullable<double> Stawka_operator { get; set; }
        public Nullable<double> Stawka_pomoc { get; set; }
        public Nullable<double> Stawka_operato_k { get; set; }
        public Nullable<double> Stawka_pomoc_k { get; set; }
    }
}
