//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAT_PRodukcja.dbProdukcjaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konfekcja
    {
        public Nullable<int> Nr_zlecenia { get; set; }
        public string Nr_sztuki { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> Godz { get; set; }
        public string Artykuł { get; set; }
        public string Numer { get; set; }
        public string NumerMG { get; set; }
        public Nullable<int> Operator { get; set; }
        public Nullable<int> Pomoc_operatora { get; set; }
        public string Szerokość { get; set; }
        public Nullable<int> Długość { get; set; }
        public Nullable<float> Waga { get; set; }
        public string Gatunek { get; set; }
        public bool Odpad { get; set; }
        public Nullable<float> Waga_odpad { get; set; }
        public Nullable<double> M2 { get; set; }
        public Nullable<System.DateTime> DataWG { get; set; }
        public Nullable<int> Nr_WZ { get; set; }
    }
}
