//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAT_PRodukcja.dbProdukcjaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn
    {
        public int Lp { get; set; }
        public string Nr_partii { get; set; }
        public Nullable<int> Nr_zlecenia { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Kontrahent { get; set; }
        public string Nazwa_surowca { get; set; }
        public int BO { get; set; }
        public int Zakup { get; set; }
        public int Produkcja { get; set; }
        public string Operacje { get; set; }
    }
}
