//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAT_PRodukcja.dbProdukcjaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Normy_zużycia
    {
        public int Id { get; set; }
        public Nullable<int> Nr_zlecenia { get; set; }
        public string Artykuł { get; set; }
        public Nullable<int> Dostawca { get; set; }
        public string Surowiec { get; set; }
        public Nullable<double> Ilość { get; set; }
    }
}
