//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAT_PRodukcja.dbProdukcjaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szarpak
    {
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> Godz { get; set; }
        public string Artykuł { get; set; }
        public Nullable<int> Operator { get; set; }
        public Nullable<int> Waga { get; set; }
    }
}
