// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsunietoKolumne_tblProdukcjaRozliczenie_RW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsunietoKolumne_tblProdukcjaRozliczenie_RW));
        
        string IMigrationMetadata.Id
        {
            get { return "202003241148500_UsunietoKolumne_tblProdukcjaRozliczenie_RW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
