// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ZmianaTypuDlaKolumny_NIP_tblFirma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZmianaTypuDlaKolumny_NIP_tblFirma));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201356370_ZmianaTypuDlaKolumny_NIP_tblFirma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
