// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataAnnot_ForeignKey_IDZlecenieProdukcyjne_tblProdukcjaZlecenieProdukcyjneMieszanka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataAnnot_ForeignKey_IDZlecenieProdukcyjne_tblProdukcjaZlecenieProdukcyjneMieszanka));
        
        string IMigrationMetadata.Id
        {
            get { return "202001032104115_DataAnnot_ForeignKey_IDZlecenieProdukcyjne_tblProdukcjaZlecenieProdukcyjneMieszanka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
