// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodanoKol_tblProdukcjaGeokomorkaPodsumowaniePrzerob1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanoKol_tblProdukcjaGeokomorkaPodsumowaniePrzerob1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005150616512_DodanoKol_tblProdukcjaGeokomorkaPodsumowaniePrzerob1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
