// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ZmianaKol_DopuszczenieNull_tblProdukcjaZlecenieProdukcyjne_Mieszanka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZmianaKol_DopuszczenieNull_tblProdukcjaZlecenieProdukcyjne_Mieszanka));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201046420_ZmianaKol_DopuszczenieNull_tblProdukcjaZlecenieProdukcyjne_Mieszanka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
