// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodanoKolumne_CzyZweryfikowano_vwZapotrzebowanieEwidencja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanoKolumne_CzyZweryfikowano_vwZapotrzebowanieEwidencja));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141812522_DodanoKolumne_CzyZweryfikowano_vwZapotrzebowanieEwidencja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
