// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodanoKol_WspZmniejszeniaMasy_tblProdukcjaGniazdoProdukcyjne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanoKol_WspZmniejszeniaMasy_tblProdukcjaGniazdoProdukcyjne));
        
        string IMigrationMetadata.Id
        {
            get { return "202009031211053_DodanoKol_WspZmniejszeniaMasy_tblProdukcjaGniazdoProdukcyjne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
