// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ZmianaDlugosciStringa_tblProdukcjaRozliczenie_Naglowek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZmianaDlugosciStringa_tblProdukcjaRozliczenie_Naglowek));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271112470_ZmianaDlugosciStringa_tblProdukcjaRozliczenie_Naglowek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
