// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodanoKol_IDProdukcjaZlecenieProdukcyjne_tblProdukcjaRuchTowar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanoKol_IDProdukcjaZlecenieProdukcyjne_tblProdukcjaRuchTowar));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261457203_DodanoKol_IDProdukcjaZlecenieProdukcyjne_tblProdukcjaRuchTowar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
