// <auto-generated />
namespace GAT_Produkcja.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Zmiany_vwZestSprzedazyAGG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmiany_vwZestSprzedazyAGG));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230958287_Zmiany_vwZestSprzedazyAGG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
